force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scan__c/Scan__c.object-meta.xml
<CustomObject>
    <label>Scan</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Scan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scan__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Scans</relationshipLabel>
    <relationshipName>Scans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scan__c/fields/Dependencies__c.field-meta.xml
<CustomField>
    <fullName>Dependencies__c</fullName>
    <label>Dependencies</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PluginScanCtl.cls
public class PluginScanCtl {
   @InvocableMethod
   public static void processResults(List<id> scanIds) {
      List<Scan__c> scans = [Select Id, Dependencies__c, Application__c from Scan__c where id in :scanIds];
      
       doProcess(scans);
   }
    
    public static void doProcess(List<Scan__c> Scans) {
        Map<id,String> scanContents = new Map<id,String>();
        for (Scan__c s: Scans) {
            s.Dependencies__c = Util.ExtractDependencies(getScanContent(s.id));
        }
        update Scans;
    }
    
    private static String getScanContent(id scanId) {
        ContentDocumentLink cd = [select ContentDocument.LatestPublishedVersion.VersionData from contentDocumentLink where linkedEntityID =:scanId];
		return (cd.ContentDocument.LatestPublishedVersion.VersionData.toString());
    }
}