force-app/main/default/objects/Application__c/Application__c.object-meta.xml
<CustomObject>
    <label>Application</label>
    <nameField>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that created this app</description>
    <label>App Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Applications</relationshipLabel>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scan__c/Scan__c.object-meta.xml
<CustomObject>
    <label>Scan</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Scan Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scan__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <referenceTo>Application__c</referenceTo>
    <relationshipLabel>Scans</relationshipLabel>
    <relationshipName>Scans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scan__c/fields/Scan_Date__c.field-meta.xml
<CustomField>
    <fullName>Scan_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Scan Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchProcessTest.cls
@isTest
private class BatchProcessTest {
    
    @testSetup
    static void setupTestData() {
        Account a = new Account(Name='Test Account');
        insert a;
        Application__c app = new Application__c();
        app.Account__c = a.id;
        app.Name = 'Test App';
        insert app;
        
        Scan__c s = new Scan__c();
        s.Application__c = app.id;
        s.Scan_Date__c = System.now();
        
        insert s;
        
        ContentVersion cv = new ContentVersion();
        cv.Title='TestScan';
        cv.PathOnClient='Test.json';
        cv.VersionData= Blob.valueof('[{"path":"./metadataPackage_1589470282990","date":"Thu 14 May 2020 11:31:25 EDT","result":""}]');
        insert cv;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=s.id;  
        contentlink.ShareType= 'I';               
        contentlink.ContentDocumentId=documents[0].Id;
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        
    }
    
    @isTest
    static void testBatch() {
        Test.startTest();
        BatchProcessScans b = new BatchProcessScans();
        Database.executeBatch(b);
        Test.stopTest();
    }
    
    @isTest
    static void testSchedule() {
        Test.startTest();
        ScheduleScanBatch ssb = new ScheduleScanBatch();
        String cron = '0 0 23 * * ?';        
        system.schedule('Test Sched', cron, ssb);
        test.stopTest();
    }
    

}